package beuth.se.ue4.client.view;

//import AbstractView

import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Style.Unit;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class FooterViewImpl extends AbstractView implements FooterView {
	private static FooterViewImplUiBinder uiBinder = GWT
			.create(FooterViewImplUiBinder.class);

	interface FooterViewImplUiBinder extends UiBinder<Widget, FooterViewImpl> {
		// TODO Generated by GWT
			//Start of user code FooterViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code Footer
	// TODO Auto generated Method
	
	private Presenter presenter;
	//End of user code
	@Inject
	public FooterViewImpl() {
		content.getElement().getStyle().setWidth(60, Unit.PC);
		content.getElement().getStyle().setHeight(2, Unit.PC);
		content.add(uiBinder.createAndBindUi(this));
		
			//Start of user code FooterViewImpl
			// TODO Auto generated Method
			//End of user code
	}

	
				
	@UiHandler({ "toImpressum" })
	public void onButtonPressed(ClickEvent e) {
		presenter.onButtonClicked(e.getRelativeElement().getInnerText());
	}		
	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code Footer
		// TODO Auto generated Method
		//End of user code
}
