package beuth.se.ue4.client.view;

//import AbstractView
import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Style.Unit;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.client.Command;
import com.google.gwt.user.client.ui.MenuItem;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class HeaderViewImpl extends AbstractView implements HeaderView {
	private static HeaderViewImplUiBinder uiBinder = GWT
			.create(HeaderViewImplUiBinder.class);

	interface HeaderViewImplUiBinder extends UiBinder<Widget, HeaderViewImpl> {
		// TODO Generated by GWT
			//Start of user code HeaderViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code Header
	// TODO Auto generated Method
	@UiField
	MenuItem toHome;

	@UiField
	MenuItem toNews;

	@UiField
	MenuItem toPortfolio;

	@UiField
	MenuItem Projects;

	@UiField
	MenuItem toImpressum;
	
	private Presenter presenter;
	//End of user code
	@Inject
	public HeaderViewImpl() {
		content.getElement().getStyle().setWidth(60, Unit.PC);
		content.getElement().getStyle().setHeight(2, Unit.PC);
		content.add(uiBinder.createAndBindUi(this));
		
		Projects.setCommand(new Command() {

			@Override
			public void execute() {
				presenter.onProjectsClicked();

			}
		});

		toNews.setCommand(new Command() {

			@Override
			public void execute() {
				presenter.onToNewsClicked();

			}
		});

		toImpressum.setCommand(new Command() {

			@Override
			public void execute() {
				presenter.onToImpressumClicked();

			}
		});

		toPortfolio.setCommand(new Command() {

			@Override
			public void execute() {
				presenter.onToPortfolioClicked();

			}
		});

		toHome.setCommand(new Command() {

			@Override
			public void execute() {
				presenter.onToHomeClicked();

			}
		});

			//Start of user code HeaderViewImpl
			// TODO Auto generated Method
			//End of user code
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code Header
		// TODO Auto generated Method
		//End of user code
}
