package beuth.se.ue4.client.view;

//import AbstractView
import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class ImpressumViewImpl extends AbstractView implements ImpressumView {
	private static ImpressumViewImplUiBinder uiBinder = GWT
			.create(ImpressumViewImplUiBinder.class);

	interface ImpressumViewImplUiBinder extends UiBinder<Widget, ImpressumViewImpl> {
		// TODO Generated by GWT
			//Start of user code ImpressumViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code Impressum
	// TODO Auto generated Method

	
	private Presenter presenter;
	//End of user code
	@Inject
	public ImpressumViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
		
			//Start of user code ImpressumViewImpl
			// TODO Auto generated Method
			//End of user code
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code Impressum
		// TODO Auto generated Method
		//End of user code
}
