package beuth.se.ue4.client.view;

//import AbstractView
import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class NewsViewImpl extends AbstractView implements NewsView {
	private static NewsViewImplUiBinder uiBinder = GWT
			.create(NewsViewImplUiBinder.class);

	interface NewsViewImplUiBinder extends UiBinder<Widget, NewsViewImpl> {
		// TODO Generated by GWT
			//Start of user code NewsViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code News
	// TODO Auto generated Method

	
	private Presenter presenter;
	//End of user code
	@Inject
	public NewsViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
		
			//Start of user code NewsViewImpl
			// TODO Auto generated Method
			//End of user code
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code News
		// TODO Auto generated Method
		//End of user code
}
