package beuth.se.ue4.client.view;

//import AbstractView
import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class ProjectsViewImpl extends AbstractView implements ProjectsView {
	private static ProjectsViewImplUiBinder uiBinder = GWT
			.create(ProjectsViewImplUiBinder.class);

	interface ProjectsViewImplUiBinder extends UiBinder<Widget, ProjectsViewImpl> {
		// TODO Generated by GWT
			//Start of user code ProjectsViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code Projects
	// TODO Auto generated Method


	
	private Presenter presenter;
	//End of user code
	@Inject
	public ProjectsViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
		
			//Start of user code ProjectsViewImpl
			// TODO Auto generated Method
			//End of user code
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code Projects
		// TODO Auto generated Method
		//End of user code
}
