package beuth.se.ue4.client.view.impressum;

//import AbstractView
import beuth.se.ue4.client.common.AbstractView;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.user.client.ui.HTML;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class ImpressumViewImpl extends AbstractView implements ImpressumView {
	private static ImpressumViewImplUiBinder uiBinder = GWT
			.create(ImpressumViewImplUiBinder.class);

	interface ImpressumViewImplUiBinder extends UiBinder<Widget, ImpressumViewImpl> {
		// TODO Generated by GWT
			//Start of user code ImpressumViewImplUiBinder
			// TODO Auto generated Method
			//End of user code
	}
	//Start of user code Impressum
	// TODO Auto generated Method

	
	private Presenter presenter;
	//End of user code
	@Inject
	public ImpressumViewImpl() {

		content.add(uiBinder.createAndBindUi(this));
			//Start of user code ImpressumViewImpl
		HTML html = new HTML("<div class=\"impressum\"><h2>Haftungsausschuss</h2>"
				+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet." 
				+ "<h2>Anderes</h2>"
				+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<div/>");
		content.add(html);
		//End of user code
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
		//Start of user code Impressum
		// TODO Auto generated Method
		//End of user code
}
