
package beuth.se.ue4.client.view;

//import AbstractView
import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class MyHeaderViewImpl extends AbstractView implements MyHeaderView {
	private static MyHeaderViewImplUiBinder uiBinder = GWT
			.create(MyHeaderViewImplUiBinder.class);

	interface MyHeaderViewImplUiBinder extends UiBinder<Widget, MyHeaderViewImpl> {
		// TODO Generated by GWT
	}




2invalid
	
	private Presenter presenter;

	@Inject
	public MyHeaderViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
}
