
package beuth.se.ue4.client.view;

//import AbstractView
import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class PortfolioViewImpl extends AbstractView implements PortfolioView {
	private static PortfolioViewImplUiBinder uiBinder = GWT
			.create(PortfolioViewImplUiBinder.class);

	interface PortfolioViewImplUiBinder extends UiBinder<Widget, PortfolioViewImpl> {
		// TODO Generated by GWT
	}
2invalid
2invalid
2invalid
2invalid
	
	private Presenter presenter;

	@Inject
	public PortfolioViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
}
