
package beuth.se.ue4.client.view;

//import AbstractView
import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;
import com.google.inject.Inject;

public class TestNewsViewImpl extends AbstractView implements NewsView {
	private static TestNewsViewImplUiBinder uiBinder = GWT
			.create(TestNewsViewImplUiBinder.class);

	interface TestNewsViewImplUiBinder extends UiBinder<Widget, TestNewsViewImpl> {
		// TODO Generated by GWT
	}
	
	private Presenter presenter;

	@Inject
	public TestNewsViewImpl() {
		content.add(uiBinder.createAndBindUi(this));
	}

	@Override
	public void setPresenter(final Presenter presenter) {
		this.presenter = presenter;
	}
}
